### ISSUE TITLE
提示  lperf: no save records  

### ISSUE THREAD

**Issue by jiangshuai377** [xingshuo/skynet-perf#1]
测试用例运行日志：
[:00000002] LAUNCH snlua bootstrap
[:00000003] LAUNCH snlua launcher
[:00000004] LAUNCH snlua cdummy
[:00000005] LAUNCH harbor 0 4
[:00000006] LAUNCH snlua datacenterd
[:00000007] LAUNCH snlua service_mgr
[:00000008] LAUNCH snlua calcsvr
[:00000000] lperf: started.
[:00000000] lperf: no save records
[:00000000] lperf: stopped.
[:00000008] KILL self
[:00000002] KILL self
生成热点图:
./pprof -i test_calc.pro -png test_calc.png
header len error

**Comment by jiangshuai377** [comment]
已解决 之前集成了 swt 的profile工具 改了snlua 的结构 要保持 lperf.h 的结构一致  
![image](https://github.com/xingshuo/skynet-perf/assets/77150611/db99adbc-9a08-4163-a2fe-45e97ec5d07f)

**Comment by jiangshuai377** [comment]
测试用例正常 但是放到项目中依然会提示
19/01/24 11:08:32.19 [:00000000] lperf: no save records
19/01/24 11:08:32.19 [:00000000] lperf: stopped.

**Comment by xingshuo** [comment]
gdb 断点一下signal_hook看看有没有走到add_record呗

**Comment by jiangshuai377** [comment]
找到原因了 是代码运行时间太短了   这种定时按帧率采样的方式不太适合局部代码分析
